#!/usr/bin/env python3
"""
Configs de mockup por módulo — sidebar, stats, chart, Olívia chat, marquee, floating card.
Usado por build_lps.py para personalizar a hero mockup e marquee em cada LP.
"""

# Marquee items: cada item é (texto, is_gold)
# Total: 12 por módulo (6 gold + 6 neutral, intercalados)

# Sidebar item: dict com label, icon (svg path data), opcional badge
# Icon path data extraído de Lucide ou Solar simples

MOCKUPS = {
    'crm': {
        # Sidebar
        'sidebar_section_1': 'Olívia',
        'sidebar_section_2': 'Comercial',
        'sidebar_section_3': 'Gestão',
        'sidebar_items_section_2': [
            ('M3 9l9 7 9-7M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z', 'Pipeline', None, True),
            ('M9 11H7a2 2 0 01-2-2V5a2 2 0 012-2h2m6 0h2a2 2 0 012 2v4a2 2 0 01-2 2h-2', 'Leads', '24', False),
            ('M12 8v4l3 3M12 2a10 10 0 110 20 10 10 0 010-20z', 'Web Forms', None, False),
            ('M13 10V3L4 14h7v7l9-11h-7z', 'Automações', None, False),
        ],
        'sidebar_items_section_3': [
            ('M9 17v-2a4 4 0 014-4h0a4 4 0 014 4v2', 'Clientes', None, False),
            ('M9 19v-6a2 2 0 012-2h2a2 2 0 012 2v6', 'Relatórios', None, False),
        ],
        # Header
        'header_title': 'Pipeline Comercial',
        'header_action': 'Novo lead',
        # Stats
        'stat_1_label': 'Total Leads',
        'stat_1_value': '2.204',
        'stat_1_change_value': '+18%',
        'stat_1_change_label': 'vs mês anterior',
        'stat_2_label': 'Em Negociação',
        'stat_2_value': 'R$ 1,8M',
        'stat_2_change_value': '+12%',
        'stat_2_change_label': 'vs mês anterior',
        'stat_3_label': 'Taxa Conversão',
        'stat_3_value': '14%',
        'stat_3_sub_left': 'Meta · 12% atingida',
        'stat_3_sub_right': 'Forte',
        # Chart
        'chart_title': 'Conversão por estágio',
        'chart_subtitle': 'Últimos 6 meses · funil completo',
        'chart_highlight': '+22% vs mês anterior',
        'chart_tooltip_value': 'R$ 612K',
        # Olívia panel (right side)
        'olivia_role': 'Sua IA comercial',
        'olivia_question': 'Qual lead devo priorizar hoje?',
        'olivia_answer_h': 'ACME Corp · score 87',
        'olivia_answer_body': 'Em proposta há 8 dias. <strong>5° contato no WhatsApp</strong>. Probabilidade de fechar essa semana: 76%.',
        'olivia_action_1': 'Ver lead',
        'olivia_action_2': 'Sugerir próx. ação',
        'olivia_input_placeholder': 'Pergunte sobre um lead...',
        # Pergunte à Olívia bottom bar
        'bottom_bar_title': 'Pergunte à Olívia',
        'bottom_bar_subtitle': 'Análise IA de leads, sugestão de próxima ação',
        'bottom_bar_input_placeholder': 'Olívia, qual lead devo abordar agora?',
        # Marquee items (texto, is_gold)
        'marquee': [
            ('3.045+ empresas BR confiam', False),
            ('IA analisa cada lead', True),
            ('WhatsApp integrado · sem extensão', False),
            ('Pipeline visual customizável', True),
            ('Web Forms criam lead automático', False),
            ('Olívia sugere próxima ação', True),
            ('2.204 leads médios por cliente', False),
            ('Automação de follow-up', True),
            ('App mobile pra vendedor em campo', False),
            ('+65% produtividade comercial', True),
            ('Conectado com Financeiro e RH', False),
            ('Análise de causa do "lead perdido"', True),
        ],
        # Floating card (LP B)
        'floating_stat': 'Pipeline ao vivo',
        'floating_label': 'sem WhatsApp pessoal. Com IA por lead.',
        # Mobile hero card chat (LP A mobile fallback)
        'mobile_role': 'Sua IA comercial',
        'mobile_question': 'Qual lead devo priorizar hoje?',
        'mobile_answer_h': 'ACME Corp · score 87',
        'mobile_answer_body': 'Em proposta há 8 dias. <strong>5° contato</strong>. 76% chance de fechar.',
        'mobile_action_1': 'Ver lead',
        'mobile_action_2': 'Próxima ação',
        # Benefícios mini-mockups
        'b1_chat_q': 'Top 3 leads quentes',
        'b1_chat_h': 'Pipeline (mai/2026)',
        'b1_chat_lines': ['1. ACME Corp · score 87', '2. Veridian · score 74', '3. Lumina · score 68'],
        'b2_chart_title': 'Conversão · 6m',
        'b2_chart_pill': 'Taxa 14% · +2pp',
        'b3_app_l1': 'Lead em proposta · ACME',
        'b3_app_v1': 'R$ 180K',
        'b3_app_l2': 'Closer · validação',
        'b3_app_v2': 'há 5min',
        'b3_app_l3': 'Diretor comercial',
        'b3_app_status': 'pendente',
        'b4_center_p': 'CRM',
        'b4_center_s': 'Olívia · IA',
    },

    'estrategico': {
        'sidebar_section_1': 'Olívia',
        'sidebar_section_2': 'Estratégia',
        'sidebar_section_3': 'Mercado',
        'sidebar_items_section_2': [
            ('M3 3h18v18H3z M3 9h18 M9 21V9', 'BSC', None, True),
            ('M9 11l3 3L22 4M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11', 'OKRs', '5/7', False),
            ('M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4', 'Missão/Visão', None, False),
            ('M9 4v16m6-16v16M3 8h18M3 16h18', 'SWOT', None, False),
        ],
        'sidebar_items_section_3': [
            ('M21 21l-4.35-4.35M16 10a6 6 0 11-12 0 6 6 0 0112 0z', 'Concorrência', '12', False),
            ('M13 7h8m0 0v8m0-8l-8 8-4-4-6 6', 'Posicionamento', None, False),
        ],
        'header_title': 'Painel Estratégico',
        'header_action': 'Nova iniciativa',
        'stat_1_label': 'BSC Progresso',
        'stat_1_value': '78%',
        'stat_1_change_value': '+6pp',
        'stat_1_change_label': 'vs trimestre',
        'stat_2_label': 'OKRs Atingidos',
        'stat_2_value': '5/7',
        'stat_2_change_value': '71%',
        'stat_2_change_label': 'meta 80%',
        'stat_3_label': 'Mercado Mapeado',
        'stat_3_value': '12 conc.',
        'stat_3_sub_left': 'IA monitora 24/7',
        'stat_3_sub_right': 'Ativo',
        'chart_title': 'BSC · 4 Perspectivas',
        'chart_subtitle': 'Score por perspectiva · trimestre',
        'chart_highlight': '+12% nos 4 quadrantes',
        'chart_tooltip_value': '92%',
        'olivia_role': 'Sua IA estrategista',
        'olivia_question': 'Como está meu BSC esse mês?',
        'olivia_answer_h': '78% geral · 4 perspectivas',
        'olivia_answer_body': 'Financeiro <strong>92%</strong>, Cliente 78%, Processos 65%, Aprendizado 70%. Atenção: Processos abaixo da meta há 2 meses.',
        'olivia_action_1': 'Ver causa raiz',
        'olivia_action_2': 'Sugerir iniciativa',
        'olivia_input_placeholder': 'Pergunte sobre BSC ou OKRs...',
        'bottom_bar_title': 'Pergunte à Olívia',
        'bottom_bar_subtitle': 'BSC, OKRs, SWOT e inteligência de mercado',
        'bottom_bar_input_placeholder': 'Olívia, qual perspectiva do BSC está mais fraca?',
        'marquee': [
            ('3.045+ empresas BR confiam', False),
            ('BSC vivo conectado a projetos', True),
            ('OKRs trimestrais auditáveis', False),
            ('SWOT atualizado em tempo real', True),
            ('IA analisa concorrência 24/7', False),
            ('Estratégia sai do PowerPoint', True),
            ('+92% alinhamento estratégia × execução', False),
            ('Agente IA Estrategista nativo', True),
            ('4 perspectivas BSC integradas', False),
            ('Inteligência de mercado em segundos', True),
            ('Reunião trimestral 70% mais rápida', False),
            ('Conectado com Financeiro, CRM, RH', True),
        ],
        'floating_stat': 'BSC vivo',
        'floating_label': 'não é mais PowerPoint empoeirado.',
        'mobile_role': 'Sua IA estrategista',
        'mobile_question': 'Como está meu BSC?',
        'mobile_answer_h': '78% geral',
        'mobile_answer_body': 'Financeiro <strong>92%</strong>, Cliente 78%, Processos 65%. Atenção em Processos.',
        'mobile_action_1': 'Ver causa',
        'mobile_action_2': 'Sugerir ação',
        # Benefícios mini-mockups
        'b1_chat_q': 'Score por perspectiva',
        'b1_chat_h': 'BSC (mai/2026)',
        'b1_chat_lines': ['Financeiro: <strong>92%</strong>', 'Cliente: 78%', 'Processos: 65%'],
        'b2_chart_title': 'BSC · 6m',
        'b2_chart_pill': 'Score 78% · +6pp',
        'b3_app_l1': 'OKR Q2 · revisão',
        'b3_app_v1': '5/7',
        'b3_app_l2': 'Sócio · validação',
        'b3_app_v2': 'há 30min',
        'b3_app_l3': 'CEO · aprovação',
        'b3_app_status': 'pendente',
        'b4_center_p': 'Estratégico',
        'b4_center_s': 'BSC · OKR',
    },

    'indicadores': {
        'sidebar_section_1': 'Olívia',
        'sidebar_section_2': 'KPIs',
        'sidebar_section_3': 'Configuração',
        'sidebar_items_section_2': [
            ('M3 3v18h18 M7 14l4-4 4 4 6-6', 'Dashboards', None, True),
            ('M12 20l9-7-9-7-9 7 9 7z', 'Indicadores', '22', False),
            ('M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z', 'Alertas', '3', False),
            ('M4 7v10c0 2 2 4 4 4h8c2 0 4-2 4-4V7M4 7c0-2 2-4 4-4h8c2 0 4 2 4 4M4 7h16', 'Categorias', None, False),
        ],
        'sidebar_items_section_3': [
            ('M9 12h6m-3-3v6m9 0a9 9 0 11-18 0 9 9 0 0118 0z', 'Conectores', '8', False),
            ('M12 6v6l4 2', 'Importações', None, False),
        ],
        'header_title': 'Painel de KPIs',
        'header_action': 'Novo KPI',
        'stat_1_label': 'KPIs ativos',
        'stat_1_value': '22',
        'stat_1_change_value': '18 na meta',
        'stat_1_change_label': '4 fora · 0 críticos',
        'stat_2_label': 'CPL Marketing',
        'stat_2_value': 'R$ 42',
        'stat_2_change_value': '−18%',
        'stat_2_change_label': 'vs mês anterior',
        'stat_3_label': 'NPS Cliente',
        'stat_3_value': '78',
        'stat_3_sub_left': '+6 pts vs trim.',
        'stat_3_sub_right': 'Promotor',
        'chart_title': 'CPL × Conversão',
        'chart_subtitle': 'Últimos 6 meses · canal Google',
        'chart_highlight': 'CPL ↓ Conversão ↑',
        'chart_tooltip_value': 'R$ 42',
        'olivia_role': 'Sua IA de indicadores',
        'olivia_question': 'Por que o CPL caiu 30% em maio?',
        'olivia_answer_h': '3 causas correlacionadas',
        'olivia_answer_body': '1) Campanha X pausou; 2) <strong>Negativadas aplicadas</strong>; 3) Match types ajustados. Conversão subiu 22% juntos.',
        'olivia_action_1': 'Ver detalhe',
        'olivia_action_2': 'Aplicar a outros KPIs',
        'olivia_input_placeholder': 'Pergunte sobre qualquer KPI...',
        'bottom_bar_title': 'Pergunte à Olívia',
        'bottom_bar_subtitle': 'Causa raiz, hipóteses e correlações em segundos',
        'bottom_bar_input_placeholder': 'Olívia, por que esse KPI caiu?',
        'marquee': [
            ('3.045+ empresas BR confiam', False),
            ('22+ KPIs prontos', True),
            ('IA explica causa raiz', False),
            ('Conectores nativos · sem ETL', True),
            ('Alertas inteligentes por meta', False),
            ('Painel único da empresa', True),
            ('80% menos tempo discutindo número', False),
            ('Integra Power BI se precisar', True),
            ('Fonte única da verdade', False),
            ('Mobile com push de alerta', True),
            ('Compartilhável com investidor', False),
            ('Decisão por dado · não por feeling', True),
        ],
        'floating_stat': 'KPI ao vivo',
        'floating_label': 'com causa raiz · não só gráfico.',
        'mobile_role': 'Sua IA de indicadores',
        'mobile_question': 'Por que o CPL caiu 30%?',
        'mobile_answer_h': '3 causas correlacionadas',
        'mobile_answer_body': 'Campanha X pausou + <strong>negativadas aplicadas</strong> + match types ajustados.',
        'mobile_action_1': 'Ver detalhe',
        'mobile_action_2': 'Replicar',
        # Benefícios mini-mockups
        'b1_chat_q': 'Top 3 KPIs em alerta',
        'b1_chat_h': 'Alertas (mai/2026)',
        'b1_chat_lines': ['1. CPL ↑ 30%', '2. Conv ↓ 5%', '3. NPS ↓ 4pt'],
        'b2_chart_title': 'CPL · 6m',
        'b2_chart_pill': 'Queda 18% · meta hit',
        'b3_app_l1': 'Alerta CPL · acima da meta',
        'b3_app_v1': 'crítico',
        'b3_app_l2': 'Olívia · causa raiz',
        'b3_app_v2': 'há 2min',
        'b3_app_l3': 'Diretor mkt · ação',
        'b3_app_status': 'pendente',
        'b4_center_p': 'Indicadores',
        'b4_center_s': '22 KPIs · IA',
    },

    'processos': {
        'sidebar_section_1': 'Olívia',
        'sidebar_section_2': 'Processos',
        'sidebar_section_3': 'ISO 9001',
        'sidebar_items_section_2': [
            ('M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2', 'Processos', '47', True),
            ('M4 6h16M4 10h16M4 14h16M4 18h16', 'Instruções de Trabalho', None, False),
            ('M22 12h-4l-3 9L9 3l-3 9H2', 'Cadeia de Valor', None, False),
            ('M9 5l7 7-7 7', 'Ciclo de Vida', None, False),
        ],
        'sidebar_items_section_3': [
            ('M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z', 'Auditoria', None, False),
            ('M12 14l9-5-9-5-9 5 9 5z', 'Departamentos', None, False),
        ],
        'header_title': 'Mapa de Processos',
        'header_action': 'Criar com IA',
        'stat_1_label': 'Processos Mapeados',
        'stat_1_value': '47',
        'stat_1_change_value': '+12 mês',
        'stat_1_change_label': 'IA acelerou em 70%',
        'stat_2_label': 'Críticos',
        'stat_2_value': '12',
        'stat_2_change_value': '100%',
        'stat_2_change_label': 'documentados',
        'stat_3_label': 'ISO 9001 Ready',
        'stat_3_value': '100%',
        'stat_3_sub_left': 'Auditoria simulada OK',
        'stat_3_sub_right': 'Pronto',
        'chart_title': 'Cadeia de Valor',
        'chart_subtitle': 'Processos por área · status',
        'chart_highlight': '47 mapeados',
        'chart_tooltip_value': '12 críticos',
        'olivia_role': 'Sua IA de processos',
        'olivia_question': 'Mapeie meu processo de compras',
        'olivia_answer_h': 'Mapa criado · 4 etapas',
        'olivia_answer_body': 'Solicitação → Cotação → Aprovação (3 níveis) → Pedido. <strong>3 gargalos identificados</strong> na aprovação. Quer ver?',
        'olivia_action_1': 'Ver fluxograma',
        'olivia_action_2': 'Otimizar aprovação',
        'olivia_input_placeholder': 'Descreva um processo pra eu mapear...',
        'bottom_bar_title': 'Pergunte à Olívia',
        'bottom_bar_subtitle': 'Agente IA mapeia processo a partir de descrição',
        'bottom_bar_input_placeholder': 'Olívia, mapeie meu processo de onboarding',
        'marquee': [
            ('3.045+ empresas BR confiam', False),
            ('Agente IA mapeia processo', True),
            ('BPMN nativo · padrão ISO', False),
            ('Cadeia de Valor visual', True),
            ('Instruções de Trabalho auto-geradas', False),
            ('ISO 9001 ready em 30 dias', True),
            ('Onboarding 3x mais rápido', False),
            ('Conhecimento sai da cabeça', True),
            ('Conectado a KPIs · tempo de ciclo medido', False),
            ('Auditoria com 1 clique', True),
            ('Versionamento e aprovação', False),
            ('Export Word, PDF, BPMN', True),
        ],
        'floating_stat': 'Processo vivo',
        'floating_label': 'não manual em PDF que ninguém lê.',
        'mobile_role': 'Sua IA de processos',
        'mobile_question': 'Mapeie processo de compras',
        'mobile_answer_h': 'Mapa criado · 4 etapas',
        'mobile_answer_body': '<strong>3 gargalos</strong> na aprovação identificados. Quer ver fluxograma?',
        'mobile_action_1': 'Ver mapa',
        'mobile_action_2': 'Otimizar',
        # Benefícios mini-mockups
        'b1_chat_q': 'Mapeie processo de compras',
        'b1_chat_h': 'Mapa criado · 4 etapas',
        'b1_chat_lines': ['Solicitação → Cotação', 'Aprovação (3 níveis)', '<strong>3 gargalos</strong> identificados'],
        'b2_chart_title': 'Processos mapeados · 6m',
        'b2_chart_pill': '47 processos · ISO ready',
        'b3_app_l1': 'Processo compras · v2.1',
        'b3_app_v1': 'novo',
        'b3_app_l2': 'Qualidade · revisão',
        'b3_app_v2': 'há 1h',
        'b3_app_l3': 'Auditor ISO · validação',
        'b3_app_status': 'pendente',
        'b4_center_p': 'Processos',
        'b4_center_s': 'BPM · ISO',
    },

    'pessoas': {
        'sidebar_section_1': 'Olívia',
        'sidebar_section_2': 'Pessoas',
        'sidebar_section_3': 'Desenvolvimento',
        'sidebar_items_section_2': [
            ('M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2M9 11a4 4 0 100-8 4 4 0 000 8z', 'Colaboradores', '52', True),
            ('M9 19c-5 0-8-3-8-8s3-8 8-8M14 5l7 7-7 7', 'Cargos', None, False),
            ('M3 3h18v18H3z M9 7h6v6H9z', 'Organograma', None, False),
            ('M3 21h18M3 10h18M5 6l7-3 7 3', 'Recrutamento', '8 vagas', False),
        ],
        'sidebar_items_section_3': [
            ('M22 11.08V12a10 10 0 11-5.93-9.14', 'PDI', None, False),
            ('M12 14l9-5-9-5-9 5 9 5z', 'Treinamentos', None, False),
        ],
        'header_title': 'Painel RH',
        'header_action': 'Nova vaga',
        'stat_1_label': 'Colaboradores',
        'stat_1_value': '52',
        'stat_1_change_value': '+4 mês',
        'stat_1_change_label': '3 em onboarding',
        'stat_2_label': 'Vagas Abertas',
        'stat_2_value': '8',
        'stat_2_change_value': '42 candidatos',
        'stat_2_change_label': '6 em entrevista',
        'stat_3_label': 'Engajamento',
        'stat_3_value': '92%',
        'stat_3_sub_left': 'Treinamento WhatsApp',
        'stat_3_sub_right': 'Alto',
        'chart_title': 'Headcount × Departamento',
        'chart_subtitle': 'Últimos 6 meses · crescimento',
        'chart_highlight': '+15% vs trimestre',
        'chart_tooltip_value': '52 colabs',
        'olivia_role': 'Sua IA de pessoas',
        'olivia_question': 'Quais skills faltam no time?',
        'olivia_answer_h': '3 gaps críticos identificados',
        'olivia_answer_body': '<strong>React Server Components</strong> (3 colabs), <strong>Kubernetes</strong> (2), <strong>FinOps</strong> (1). Sugiro trilha via microlearning.',
        'olivia_action_1': 'Criar PDI',
        'olivia_action_2': 'Sugerir trilha',
        'olivia_input_placeholder': 'Pergunte sobre o time ou skills...',
        'bottom_bar_title': 'Pergunte à Olívia',
        'bottom_bar_subtitle': 'PDI, skill gap, recrutamento e desenvolvimento',
        'bottom_bar_input_placeholder': 'Olívia, qual o gap de competência do time?',
        'marquee': [
            ('3.045+ empresas BR confiam', False),
            ('ATS de recrutamento nativo', True),
            ('Treinamento via WhatsApp', False),
            ('92% engajamento em microlearning', True),
            ('Organograma multi-modo vivo', False),
            ('PDI conectado a cargo e skill', True),
            ('Avaliação 360 nativa', False),
            ('Banco de talentos infinito', True),
            ('40% menos tempo em recrutamento', False),
            ('Substitui Gupy + Kenoby + BambooHR', True),
            ('Conectado com Financeiro · folha futura', False),
            ('Skill gap detectado por IA', True),
        ],
        'floating_stat': 'RH integrado',
        'floating_label': 'do recrutamento ao desenvolvimento.',
        'mobile_role': 'Sua IA de pessoas',
        'mobile_question': 'Quais skills faltam?',
        'mobile_answer_h': '3 gaps críticos',
        'mobile_answer_body': '<strong>React (3)</strong>, K8s (2), FinOps (1). Trilha sugerida.',
        'mobile_action_1': 'Criar PDI',
        'mobile_action_2': 'Trilha',
        # Benefícios mini-mockups
        'b1_chat_q': 'Quais skills faltam no time?',
        'b1_chat_h': '3 gaps críticos',
        'b1_chat_lines': ['<strong>React RSC</strong>: 3 colabs', '<strong>Kubernetes</strong>: 2 colabs', '<strong>FinOps</strong>: 1 colab'],
        'b2_chart_title': 'Engajamento · 6m',
        'b2_chart_pill': '92% · microlearning WA',
        'b3_app_l1': 'Vaga · Eng Sr React',
        'b3_app_v1': '42 cand.',
        'b3_app_l2': 'RH · triagem',
        'b3_app_v2': '8 selec.',
        'b3_app_l3': 'CTO · entrevista final',
        'b3_app_status': 'pendente',
        'b4_center_p': 'Pessoas',
        'b4_center_s': 'RH · ATS · PDI',
    },

    'projetos': {
        'sidebar_section_1': 'Olívia',
        'sidebar_section_2': 'Projetos',
        'sidebar_section_3': 'Pessoas',
        'sidebar_items_section_2': [
            ('M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2', 'Projetos', '14', True),
            ('M9 12h6m-3-3v6m9 0a9 9 0 11-18 0 9 9 0 0118 0z', 'Tarefas', '124', False),
            ('M8 7V3m8 4V3M3 11h18M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z', 'Cronograma', None, False),
            ('M22 11.08V12a10 10 0 11-5.93-9.14', 'Alertas', '2', False),
        ],
        'sidebar_items_section_3': [
            ('M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2', 'Membros', None, False),
            ('M3 3h18v18H3z', 'Pastas', None, False),
        ],
        'header_title': 'Painel de Projetos',
        'header_action': 'Criar com IA',
        'stat_1_label': 'Projetos Ativos',
        'stat_1_value': '14',
        'stat_1_change_value': '12 no prazo',
        'stat_1_change_label': '2 com alerta',
        'stat_2_label': 'On-time',
        'stat_2_value': '86%',
        'stat_2_change_value': '+12pp',
        'stat_2_change_label': 'vs trimestre',
        'stat_3_label': 'Risco Próximo',
        'stat_3_value': '1 alto',
        'stat_3_sub_left': 'Projeto X · 14 dias',
        'stat_3_sub_right': 'Atenção',
        'chart_title': 'Burndown · 6 meses',
        'chart_subtitle': 'Entregas vs planejado',
        'chart_highlight': 'Ritmo +18%',
        'chart_tooltip_value': '14 entregues',
        'olivia_role': 'Sua IA de projetos',
        'olivia_question': 'Quais projetos vão atrasar?',
        'olivia_answer_h': '2 com risco preditivo',
        'olivia_answer_body': '<strong>Projeto X</strong>: capacity do time Y baixa (87%). <strong>Projeto Z</strong>: dependência externa em atraso. Replanejar agora?',
        'olivia_action_1': 'Ver riscos',
        'olivia_action_2': 'Replanejar',
        'olivia_input_placeholder': 'Pergunte sobre projetos ou tarefas...',
        'bottom_bar_title': 'Pergunte à Olívia',
        'bottom_bar_subtitle': 'Alertas preditivos, replanejamento, criação com IA',
        'bottom_bar_input_placeholder': 'Olívia, quais projetos têm risco esta semana?',
        'marquee': [
            ('3.045+ empresas BR confiam', False),
            ('"Criar com IA" em segundos', True),
            ('Cards, Kanban, Lista, Gantt', False),
            ('Alertas preditivos de atraso', True),
            ('86% de projetos no prazo', False),
            ('Conectado ao BSC estratégico', True),
            ('60% menos reunião de status', False),
            ('App mobile pra gestor', True),
            ('Orçado × Realizado nativo', False),
            ('IA aprende padrões da empresa', True),
            ('Substitui Asana + Monday + Trello', False),
            ('Alocação puxando do RH', True),
        ],
        'floating_stat': 'Atraso previsto',
        'floating_label': 'antes do cliente reclamar.',
        'mobile_role': 'Sua IA de projetos',
        'mobile_question': 'Quais projetos vão atrasar?',
        'mobile_answer_h': '2 com risco preditivo',
        'mobile_answer_body': '<strong>Projeto X</strong>: capacity baixa. <strong>Z</strong>: dependência externa.',
        'mobile_action_1': 'Ver riscos',
        'mobile_action_2': 'Replanejar',
        # Benefícios mini-mockups
        'b1_chat_q': 'Quais projetos vão atrasar?',
        'b1_chat_h': '2 com risco preditivo',
        'b1_chat_lines': ['<strong>Projeto X</strong> · capacity 87%', '<strong>Projeto Z</strong> · dep. externa', 'Replanejar agora?'],
        'b2_chart_title': 'Burndown · 6m',
        'b2_chart_pill': '86% on-time · +12pp',
        'b3_app_l1': 'Projeto X · mudança escopo',
        'b3_app_v1': 'risco',
        'b3_app_l2': 'PMO · análise',
        'b3_app_v2': 'há 10min',
        'b3_app_l3': 'Cliente · aprovação',
        'b3_app_status': 'pendente',
        'b4_center_p': 'Projetos',
        'b4_center_s': 'PMO · IA',
    },

    'canal-orbit': {
        'sidebar_section_1': 'Olívia',
        'sidebar_section_2': 'Meus Clientes',
        'sidebar_section_3': 'Operação',
        'sidebar_items_section_2': [
            ('M16 21v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2M22 21v-2a4 4 0 00-3-3.87M16 3.13a4 4 0 010 7.75', 'Clientes Ativos', '18', True),
            ('M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4', 'Plataforma', None, False),
            ('M9 19c-5 0-8-3-8-8s3-8 8-8', 'Agentes IA', '7', False),
            ('M2 17l10 5 10-5M2 12l10 5 10-5M12 2L2 7l10 5 10-5-10-5z', 'White-label', None, False),
        ],
        'sidebar_items_section_3': [
            ('M3 3h18v18H3z M3 9h18', 'Recorrência', None, False),
            ('M9 19v-6a2 2 0 012-2h2a2 2 0 012 2v6', 'Relatórios', None, False),
        ],
        'header_title': 'Painel Canal Orbit',
        'header_action': 'Novo cliente',
        'stat_1_label': 'Clientes Ativos',
        'stat_1_value': '18',
        'stat_1_change_value': '+3 mês',
        'stat_1_change_label': '96% retenção',
        'stat_2_label': 'MRR',
        'stat_2_value': 'R$ 124k',
        'stat_2_change_value': '+22%',
        'stat_2_change_label': 'vs mês anterior',
        'stat_3_label': 'Churn Risk',
        'stat_3_value': '1 cliente',
        'stat_3_sub_left': '30 dias sem acesso',
        'stat_3_sub_right': 'Olhar',
        'chart_title': 'MRR · 6 meses',
        'chart_subtitle': 'Crescimento e churn',
        'chart_highlight': '+22% MoM',
        'chart_tooltip_value': 'R$ 124K',
        'olivia_role': 'Sua IA do canal',
        'olivia_question': 'Qual cliente precisa de atenção?',
        'olivia_answer_h': 'Cliente Y · risco de churn',
        'olivia_answer_body': '<strong>30 dias sem acessar</strong>. Último login: BSC. Padrão semelhante ao churn da Empresa Z em jan. Acionar reunião?',
        'olivia_action_1': 'Ver atividade',
        'olivia_action_2': 'Agendar reunião',
        'olivia_input_placeholder': 'Pergunte sobre seus clientes...',
        'bottom_bar_title': 'Pergunte à Olívia',
        'bottom_bar_subtitle': 'Acompanhe seus clientes em tempo real',
        'bottom_bar_input_placeholder': 'Olívia, quem está com risco de churn?',
        'marquee': [
            ('+25 consultorias no Canal', False),
            ('White-label nativo · sua marca', True),
            ('7 agentes IA inclusos', False),
            ('Recorrência mensal embutida', True),
            ('3x mais valor · mesmo time', False),
            ('Acesso direto à operação do cliente', True),
            ('MRR previsível · churn medido', False),
            ('Domínio próprio (clientes.suacons.com.br)', True),
            ('Suporte e CS por sua equipe', False),
            ('+40% margem por cliente', True),
            ('Modelo SaaS com unit economics', False),
            ('Para consultorias R$ 100k+/mês', True),
        ],
        'floating_stat': '3x mais valor',
        'floating_label': 'sem contratar mais consultor.',
        'mobile_role': 'Sua IA do canal',
        'mobile_question': 'Qual cliente precisa atenção?',
        'mobile_answer_h': 'Cliente Y · risco de churn',
        'mobile_answer_body': '<strong>30 dias sem acessar</strong>. Padrão semelhante a churns anteriores.',
        'mobile_action_1': 'Ver atividade',
        'mobile_action_2': 'Reunião',
        # Benefícios mini-mockups
        'b1_chat_q': 'Qual cliente em risco?',
        'b1_chat_h': 'Cliente Y · churn risk',
        'b1_chat_lines': ['<strong>30 dias</strong> sem acessar', 'Padrão de churn similar', 'Acionar reunião?'],
        'b2_chart_title': 'MRR · 6m',
        'b2_chart_pill': 'R$ 124k · +22% MoM',
        'b3_app_l1': 'Novo cliente · contrato',
        'b3_app_v1': 'R$ 8k/mês',
        'b3_app_l2': 'CS · onboarding',
        'b3_app_v2': 'em prog.',
        'b3_app_l3': 'Sócio · validação',
        'b3_app_status': 'pendente',
        'b4_center_p': 'Canal Orbit',
        'b4_center_s': 'White-label',
    },
}
